import { configureStore } from "@reduxjs/toolkit";
import { cryptoApi } from "../services/cryptoApi";

export default configureStore({
    reducer: {
        [cryptoApi.reducerPath]: cryptoApi.reducer,
    },
    // @learning @custom the middleware generated by RTK-Query (RTK-Query is a powerful data fetching and caching tool in the Redux toolkit) for your crypto API. Adding it to your store configuration ensures that all the automatic data fetching, caching, and real-time update features of RTK-Query will work correctly for your crypto data
    middleware: (getDefaultMiddleware) =>
        getDefaultMiddleware().concat(cryptoApi.middleware)
});